
spring:
  jpa:
      database: h2
      hibernate:
        ddl-auto: update
      show-sql: true
  h2:
    console:
      path: /h2-console
      enabled: true
  datasource:
      url: jdbc:h2:~/test
      driver-class-name: org.h2.Driver
      username: sa
      password: 123456
#  datasource:
#    data-password: root
#    data-username: root
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/cu?useUnicode=true&characterEncoding=utf8&useSSL=false
#    type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 80

#knife4j:
#  basic:
#    enable: false
#    username: zhangsan
#    password: 123456